version: 1.1.1.{build}
os: Visual Studio 2015
environment:
  NUGETKEY:
    secure: z2fJQckgBQJ7IKfjOyrZYPM2+xDj4xYuqaUDBG7MrJs+b1bNc0vzYMTxpF6Sb1mA
  COVERALLSKEY:
    secure: ekeqd+f2UPHPJjioylOD/RFtZobq7I2ga4m+VnLexj8lJGa4Kb5v+TdZUT2fp7gQ
test: off
build_script:
- cmd: build.cmd ci nugetkey=%NUGETKEY% nugetpublishurl=https://www.myget.org/F/saladlab/api/v2/package nugetprerelease=%APPVEYOR_BUILD_NUMBER% coverallskey=%COVERALLSKEY%
artifacts:
  - path: './bin/nuget/*.nupkg'
    name: NugetPackage
  - path: './bin/unity/*.unitypackage'
    name: UnityPackage
cache:
- packages -> **\packages.config
