// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.1.2")]
[assembly: AssemblyFileVersionAttribute("1.1.2")]
[assembly: AssemblyInformationalVersionAttribute("1.1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.2";
        internal const string InformationalVersion = "1.1.2";
    }
}
